name: e_commerce
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  logger: ^2.5.0
  bloc: ^9.0.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  go_router: ^15.1.1
  fluttertoast: ^8.2.12
  flutter_svg: ^2.1.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Gabarito
      fonts:
        - asset: assets/fonts/Gabarito/Gabarito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gabarito/Gabarito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gabarito/Gabarito-Bold.ttf
          weight: 700

  uses-material-design: true
